name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2
        
    - name: Make Gradle executable
      run: chmod +x ./gradlew
        
    - name: Build Debug APK
      run: |
        ./gradlew clean
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: wifi-monitor-debug
        path: |
          app/build/outputs/apk/debug/
          !app/build/outputs/apk/debug/output-metadata.json